#!/usr/bin/env python3
"""Generate Dockerfile.matched from the host's ACTUAL environment.

Condition B is the whole point of the three-condition design: it isolates the
cost of containerisation by holding the software stack constant. If its pins do
not match the host exactly, B - A measures the pins as well, and the experiment
reproduces the flaw it was built to remove.

The pins therefore cannot be written by hand. Run this ON THE HOST, in the same
interpreter that condition A will use, immediately before building the image:

    python3 make_matched_dockerfile.py > Dockerfile.matched

It reads the running interpreter and the installed package versions, picks the
matching python:X.Y-slim-<suite> base image, and emits a Dockerfile that pins
every one of them. It refuses to emit anything if a package the inference path
imports is missing, because a silently absent pin is exactly the failure mode
this file exists to prevent.
"""
from __future__ import annotations

import platform
import sys
from pathlib import Path
from datetime import datetime, timezone

# Everything the inference path imports, plus the I2C library for supply
# telemetry. If you add an import to profile_run.py, add it here too.
REQUIRED = ["onnxruntime", "numpy", "opencv-python-headless", "psutil", "smbus2"]
OPTIONAL = ["requests"]

# The base image is debian:<suite>-slim with the distribution's own python3,
# NOT python:X.Y-slim-<suite>.
#
# The python:* images carry CPython built by python.org. The host runs the one
# Debian ships. Those differ in patch level and in build configuration, and the
# difference shows up as the only mismatch in an otherwise identical
# fingerprint. Installing the distribution's python3 on the matching suite
# makes the interpreter the same package the host is running, which is what
# "matched" has to mean if B - A is to isolate containerisation alone.
SUITE_BY_GLIBC = [
    (2.41, "trixie"),    # Debian 13
    (2.36, "bookworm"),  # Debian 12
    (2.31, "bullseye"),  # Debian 11
]


def host_suite() -> str | None:
    """Prefer the codename the host actually reports over inferring it."""
    try:
        for line in Path("/etc/os-release").read_text().splitlines():
            if line.startswith("VERSION_CODENAME="):
                return line.split("=", 1)[1].strip().strip('"') or None
    except Exception:
        pass
    return None


def version_of(dist: str) -> str | None:
    from importlib.metadata import PackageNotFoundError, version
    try:
        return version(dist)
    except PackageNotFoundError:
        return None


def host_glibc() -> float | None:
    try:
        v = platform.libc_ver()[1]
        return float(".".join(v.split(".")[:2]))
    except Exception:
        return None


def main() -> None:
    py = f"{sys.version_info.major}.{sys.version_info.minor}"
    glibc = host_glibc()

    suite = host_suite()
    inferred = False
    if suite is None:
        inferred = True
        suite = "bookworm"
        if glibc is not None:
            for floor, name in SUITE_BY_GLIBC:
                if glibc >= floor:
                    suite = name
                    break

    pins, missing = [], []
    for dist in REQUIRED:
        v = version_of(dist)
        (pins if v else missing).append(f"{dist}=={v}" if v else dist)
    if missing:
        sys.exit("refusing to emit a Dockerfile: these packages are not "
                 "installed in the interpreter you just ran, so condition B "
                 "cannot be matched to condition A:\n  "
                 + "\n  ".join(missing)
                 + "\n\nInstall the full inference environment on the host "
                   "first, then run this again with that interpreter.")
    for dist in OPTIONAL:
        v = version_of(dist)
        if v:
            pins.append(f"{dist}=={v}")

    body = " \\\n        ".join(pins)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    print(f"""# Condition B — version-MATCHED container.
#
# GENERATED by make_matched_dockerfile.py on {stamp}.
# Do not edit the pins by hand. Regenerate this file if the host environment
# changes, and rebuild the image before any further runs.
#
# Host at generation time:
#   Python  {platform.python_version()}  (Debian package, not python.org)
#   suite   {suite}{'  [inferred from glibc]' if inferred else '  [from /etc/os-release]'}
#   glibc   {glibc if glibc is not None else 'unknown'}
#   machine {platform.machine()}
#   kernel  {platform.release()}
#
# Every component below is pinned to the version the host was running, so that
# B - A isolates the cost of containerisation with the software stack held
# constant, and C - B isolates the cost of the image's runtime version with the
# execution mode held constant.
#
# Build:  docker build -f Dockerfile.matched -t infer:matched .
FROM debian:{suite}-slim

# The distribution's own python3 — the same package the host runs.
RUN apt-get update && apt-get install -y --no-install-recommends \\
        python3 \\
        python3-venv \\
        procps \\
    && rm -rf /var/lib/apt/lists/*

# A venv, as on the host, so pip installs into the same kind of environment
# and PEP 668 does not force --break-system-packages.
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN /venv/bin/pip install --no-cache-dir --upgrade pip \\
 && /venv/bin/pip install --no-cache-dir \\
        {body}

WORKDIR /app
COPY profile_run.py provenance.py basil_mobilenet.onnx ./
CMD ["/venv/bin/python", "profile_run.py", "--condition", "matched"]
""")


if __name__ == "__main__":
    main()
