#!/usr/bin/env python3
"""Emit LaTeX macros and the results table from out/numbers_v2.json.

Every measured result quoted in the paper's text, tables and abstract is a
macro defined here, so the text cannot drift from the data. (Design constants
such as the run length, cooling threshold or t quantiles are written in the
text.) The first-campaign values are read
from the repository's earlier analysis (../../analysis/numbers.json, produced
by analysis/recompute.py from data/profiling_runs). Run after analyse_v2.py.
"""
from __future__ import annotations
import json, os
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
OUT = Path(os.environ.get("OUT_DIR", HERE.parent / "out"))
FIRST_JSON = Path(os.environ.get("FIRST_JSON", HERE.parent.parent / "analysis" / "numbers.json"))
N = json.loads((OUT / "numbers_v2.json").read_text())
R, C, E = N["runs"], N["conditions"], N["effects"]
CN = {"native": "A", "matched": "B", "legacy": "C"}
EN = {"B_minus_A": "BA", "C_minus_B": "CB", "C_minus_A": "CA"}

lines = ["% generated by make_tex.py from out/numbers_v2.json -- do not edit"]


def m(name, val):
    lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")


def f(x, d):
    s = f"{x:.{d}f}"
    return s.replace("-", "\\textminus ") if s.startswith("-") else s


def sgn(x, d):
    return f"{x:+.{d}f}".replace("-", "\\textminus ")


def big(n):
    return f"{n:,}".replace(",", "{,}")


# ------------------------------------------------------------ per-metric macros
SHORT = {"latency_ms_mean": ("LatMean", 2), "latency_ms_median": ("LatMed", 2),
         "latency_ms_p95": ("LatPninetyfive", 2), "latency_ms_p99": ("LatPninetynine", 2),
         "latency_ms_sd": ("LatSD", 2), "latency_ms_p01": ("LatPone", 1),
         "fast_mode_pct": ("Fast", 0), "cpu_pct_frame_mean": ("CPU", 1),
         "cpu_ms_per_inference": ("CPUms", 1),
         "power_w_active": ("PAct", 2), "power_w_sleep": ("PSlp", 2),
         "power_w_sleep_floor": ("PFloor", 2), "power_w_sleep_hold": ("PHold", 2),
         "power_w_overall": ("PAll", 2), "energy_per_inference_gross_mJ": ("EGross", 1),
         "energy_per_inference_net_mJ": ("ENet", 1), "energy_per_inference_cycle_mJ": ("ECyc", 1),
         "energy_per_inference_above_floor_mJ": ("EInc", 1),
         "baseline_floor_per_inference_mJ": ("EBase", 1),
         "energy_per_cycle_J": ("ECycleJ", 1), "cyclic_peak_c_mean": ("TPeak", 1),
         "temp_c_mean_active": ("TAct", 1), "temp_c_max": ("TMax", 1),
         "fan_rpm_mean_active": ("Fan", 0), "fps": ("FPS", 2),
         "cpu_mhz_active_mean": ("MHz", 0)}

for key, (nm, d) in SHORT.items():
    for c, L in CN.items():
        m(f"{nm}{L}", f(C[c][key]["mean"], d))
        m(f"{nm}sd{L}", f(C[c][key]["sd"], d))
    for ek, EL in EN.items():
        e = E[key][ek]
        m(f"{nm}{EL}", sgn(e["mean"], d))
        m(f"{nm}{EL}abs", f(abs(e["mean"]), d))
        m(f"{nm}{EL}lo", f(e["ci95"][0], d))
        m(f"{nm}{EL}hi", f(e["ci95"][1], d))
        m(f"{nm}{EL}pct", sgn(e["pct_of_base"], 1))
        m(f"{nm}{EL}pctabs", f(abs(e["pct_of_base"]), 1))
        base = e["mean"] / (e["pct_of_base"] / 100) if e["pct_of_base"] else float("nan")
        m(f"{nm}{EL}pctlo", f(100 * e["ci95"][0] / base, 1))
        m(f"{nm}{EL}pcthi", f(100 * e["ci95"][1] / base, 1))
        pb = e["per_block"]
        for w, v in zip(("One", "Two", "Three"), pb):
            m(f"{nm}{EL}blk{w}", sgn(v, d))
            m(f"{nm}{EL}blk{w}abs", f(abs(v), d))
        m(f"{nm}{EL}blkmin", f(min(pb, key=abs), d))
        m(f"{nm}{EL}blkmax", f(max(pb, key=abs), d))

# per-run ranges used in the latency-mode paragraph
for c, L in CN.items():
    fr = [R[f"{c}_{i}"]["fast_mode_pct"] for i in (1, 2, 3)]
    p1 = [R[f"{c}_{i}"]["latency_ms_p01"] for i in (1, 2, 3)]
    mn = [R[f"{c}_{i}"]["latency_ms_min"] for i in (1, 2, 3)]
    m(f"Fast{L}lo", f(min(fr), 0)); m(f"Fast{L}hi", f(max(fr), 0))
    m(f"Pone{L}lo", f(min(p1), 1)); m(f"Pone{L}hi", f(max(p1), 1))
    m(f"LatMin{L}", f(min(mn), 1))
m("FastMs", f(N["design"]["fast_mode_ms"], 1))
m("SettleS", f(N["design"]["settle_s"], 0))
m("WarmupS", f(N["design"]["warmup_s"], 0))

# ------------------------------------------------------------ derived quantities
ba, ca = E["latency_ms_mean"]["B_minus_A"]["mean"], E["latency_ms_mean"]["C_minus_A"]["mean"]
cb = E["latency_ms_mean"]["C_minus_B"]["mean"]
m("ShareContainer", f(100 * ba / ca, 0))
m("ShareStack", f(100 * (ca - ba) / ca, 0))
m("StackToContainerRatio", f(cb / ba, 1))
m("LatMeanCBabsOne", f(abs(cb), 1))
m("CPUmsCBabsInt", f(abs(E["cpu_ms_per_inference"]["C_minus_B"]["mean"]), 0))
# the current stack's time per inference relative to the legacy stack's
m("StackTimeSavedPct", f(100 * cb / C["legacy"]["latency_ms_mean"]["mean"], 0))
# ... and its energy above the floor relative to the legacy stack's
inc_cb = E["energy_per_inference_above_floor_mJ"]["C_minus_B"]["mean"]
m("StackIncExtraPct", f(100 * -inc_cb / C["legacy"]["energy_per_inference_above_floor_mJ"]["mean"], 0))
for c, L in CN.items():
    share = 100 * C[c]["baseline_floor_per_inference_mJ"]["mean"] / C[c]["energy_per_inference_cycle_mJ"]["mean"]
    m(f"EBaseShare{L}", f(share, 0))
shares = [100 * C[c]["baseline_floor_per_inference_mJ"]["mean"] / C[c]["energy_per_inference_cycle_mJ"]["mean"]
          for c in CN]
m("EBaseShareLo", f(min(shares), 0)); m("EBaseShareHi", f(max(shares), 0))
ecyc_cb = E["energy_per_inference_cycle_mJ"]["C_minus_B"]["mean"]
m("IncShareOfStackEnergy", f(100 * inc_cb / ecyc_cb, 0))
# governor hold after each active phase
hold_mj = [1000 * (R[l]["power_w_sleep_hold"] - R[l]["power_w_sleep_floor"]) * N["design"]["settle_s"]
           / (R[l]["frames"] / R[l]["cycles_analysed"]) for l in R]
hold_w = [R[l]["power_w_sleep_hold"] - R[l]["power_w_sleep_floor"] for l in R]
m("HoldWlo", f(min(hold_w), 2)); m("HoldWhi", f(max(hold_w), 2))
m("HoldmJ", f(np.mean(hold_mj), 0))
m("TActS", f(np.mean([R[l]["active_len_s"] for l in R]), 2))
m("TSlpS", f(np.mean([R[l]["sleep_len_s"] for l in R]), 2))

# ------------------------------------------------------------ run integrity
m("TotFramesMin", big(min(R[l]["frames_total"] for l in R)))
m("TotFramesMax", big(max(R[l]["frames_total"] for l in R)))
m("FramesAll", big(sum(R[l]["frames_total"] for l in R)))
fps_pinned = [R[l]["fps"] for l in R if l not in ("legacy_1", "matched_1")]
m("FPSPinnedMin", f(min(fps_pinned), 2)); m("FPSPinnedMax", f(max(fps_pinned), 2))
m("FPSEarlyMin", f(min(R["legacy_1"]["fps"], R["matched_1"]["fps"]), 2))
m("FPSEarlyMax", f(max(R["legacy_1"]["fps"], R["matched_1"]["fps"]), 2))
m("CapSamples", str(sum(R[l]["cap_below_hw_max_samples"] for l in R)))
m("UVSamples", str(sum(R[l]["undervolt_samples"] for l in R)))
m("BatIMin", f(min(R[l]["bat_i_ma_min_whole"] for l in R), 0))
m("BatIMax", f(max(R[l]["bat_i_ma_max_whole"] for l in R), 0))
m("BatIMeanMin", f(min(R[l]["bat_i_ma_mean_whole"] for l in R), 1))
m("BatIMeanMax", f(max(R[l]["bat_i_ma_mean_whole"] for l in R), 1))
m("BatWMax", f(max(R[l]["bat_charge_w_mean_whole"] for l in R), 2))
m("PVIDev", f(max(abs(R[l]["bus_i_vs_p_over_v_pct"]) for l in R), 1))
m("MHzMin", f(min(R[l]["cpu_mhz_active_mean"] for l in R), 0))
m("CyclesAnalysed", str(R["native_1"]["cycles_analysed"]))
m("TMaxAll", f(max(max(R[l]["temp_c_max_whole_1hz"], R[l]["temp_c_max_whole_frame"]) for l in R), 1))

# ------------------------------------------------------------ sensitivity: blocks 2 and 3
T975_DF1 = 12.706204736174705
for key, nm, d in (("latency_ms_mean", "LatMean", 2),
                   ("energy_per_inference_above_floor_mJ", "EInc", 1),
                   ("energy_per_inference_cycle_mJ", "ECyc", 1),
                   ("cpu_pct_frame_mean", "CPU", 1)):
    for ek, EL in (("B_minus_A", "BA"), ("C_minus_B", "CB")):
        d2 = np.array(E[key][ek]["per_block"][1:])
        mu, half = d2.mean(), T975_DF1 * d2.std(ddof=1) / np.sqrt(2)
        m(f"{nm}{EL}sens", sgn(mu, d))
        basev = np.mean([R[l][key] for b in ("2", "3") for l in N["design"]["blocks"][b]["runs"]
                         if R[l]["condition"] == ("native" if ek == "B_minus_A" else "matched")])
        m(f"{nm}{EL}senspct", sgn(100 * mu / basev, 1))
        m(f"{nm}{EL}senslo", f(mu - half, d)); m(f"{nm}{EL}senshi", f(mu + half, d))

# ------------------------------------------------------------ first campaign
F = json.loads(FIRST_JSON.read_text())["conditions"]
bm, ct = F["bare-metal"], F["container"]
m("FirstLatPct", f(100 * (ct["latency_ms_mean"] - bm["latency_ms_mean"]) / bm["latency_ms_mean"], 1))
m("FirstCPUpp", f(abs(ct["cpu_pct_mean"] - bm["cpu_pct_mean"]), 2))
m("FirstPW", f(abs(ct["power_w_mean"] - bm["power_w_mean"]), 3))
m("FirstPeak", f(abs(ct["cyclic_peak_temp_c_mean"] - bm["cyclic_peak_temp_c_mean"]), 2))

(OUT / "numbers_v2.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {OUT / 'numbers_v2.tex'} ({len(lines) - 1} macros)")

# ------------------------------------------------------------ results table
ROWS2 = [("fps", "Inference rate (frame/s)", 2),
         ("latency_ms_mean", "Latency, mean (ms)", 2),
         ("latency_ms_median", "Latency, median (ms)", 2),
         ("latency_ms_p95", "Latency, p95 (ms)", 2),
         ("latency_ms_p99", "Latency, p99 (ms)", 2),
         ("cpu_pct_frame_mean", "CPU utilisation, system (\\%)", 1),
         ("cpu_ms_per_inference", "CPU time per inference (ms)", 1),
         ("power_w_active", "Power, active phase (W)", 2),
         ("power_w_sleep", "Power, sleep phase (W)", 2),
         ("power_w_sleep_floor", "Power, settled floor (W)", 2),
         ("energy_per_inference_above_floor_mJ", "Energy/inference above floor (mJ)", 1),
         ("energy_per_inference_cycle_mJ", "Energy/inference, cycle (mJ)", 1),
         ("cyclic_peak_c_mean", "Cyclic peak temperature ($^\\circ$C)", 1),
         ("fan_rpm_mean_active", "Fan speed, active phase (rpm)", 0)]


def cell(mu, sd, d):
    return f"{f(mu, d)} $\\pm$ {f(sd, d)}"


def signs(e):
    return "".join("+" if v > 0 else ("$-$" if v < 0 else "0") for v in e["per_block"])


def eff(e, d):
    dag = "" if e["ci_excludes_zero"] else "$^{\\dagger}$"
    return (f"{sgn(e['mean'], d)}{dag}", f"[{f(e['ci95'][0], d)}, {f(e['ci95'][1], d)}]", signs(e))


t = [r"\begin{table*}[t]", r"\centering",
     r"\caption{Condition means ($\pm$ SD over three runs) and within-block effects with 95\% confidence intervals ($t$, 2 d.f.). "
     r"$^{\dagger}$: interval includes zero. Signs: direction of the difference in blocks 1, 2 and 3. "
     r"CPU utilisation is system-wide, sampled per frame in the active phase. The settled floor is the sleep-phase power after the governor has stepped down; "
     r"energy per inference above the floor and over the whole duty cycle are defined in Section~\ref{sec:energy}.}",
     r"\label{tab:results}", r"\setlength{\tabcolsep}{3.5pt}", r"\scriptsize",
     r"\begin{tabular}{lccc ccc ccc}", r"\toprule",
     r" & \multicolumn{3}{c}{Condition mean $\pm$ SD} & \multicolumn{3}{c}{$B-A$ (execution mode)} & \multicolumn{3}{c}{$C-B$ (software stack)}\\",
     r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
     r"Quantity & A native & B matched & C legacy & effect & 95\% CI & signs & effect & 95\% CI & signs\\", r"\midrule"]
for key, lab, d in ROWS2:
    a, b, c = (C[x][key] for x in ("native", "matched", "legacy"))
    e1, i1, s1 = eff(E[key]["B_minus_A"], d)
    e2, i2, s2 = eff(E[key]["C_minus_B"], d)
    t.append(f"{lab} & {cell(a['mean'], a['sd'], d)} & {cell(b['mean'], b['sd'], d)} & "
             f"{cell(c['mean'], c['sd'], d)} & {e1} & {i1} & {s1} & {e2} & {i2} & {s2}\\\\")
t += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
(OUT / "table_results.tex").write_text("\n".join(t) + "\n")
print(f"wrote {OUT / 'table_results.tex'}")
